
USSF_AL_OpenCup: # Index is not used
    
  info:     
    id: USSF_AL_OpenCup_Spring2014
                
    slugs: [opencup, opencup2014]
                  
    fed:     USSF
    fedRole: USSFC
        
    fedId:     USSF
    fedRoleId: USSFC
                
    title:   "Open Cup 2014"
    desc:    "USSF Open Cup 2014 - Decatur, Alabama - April 11,12,13"
    
    general_url:  http://www.premiersoccerservices.com/home/566816.html
    
    status:    Active
    verified:  Yes
                
    season:    SP2014
    sport:     Soccer
    group:     ALYS
    groupSub:  Open Cup

    domain:    USSF
    domainSub: USSF_AL
                                
    submit:  "Emails your application to Art Hundiak and yourself."
    prefix:   OpenCup
             
    assignor:
      name:  "Art Hundiak"
      email: "ahundiak@gmail.com"
      phone:  256.457.5943
                 
  basic:
    refereeLevel:
      type:    select
      label:   Level to Referee At
      default: Competitive
      choices: { Competitive: Competitive, Elite: Elite, Recreational: Recreational }
                                                
    comfortLevelCenter:
      type:    select
      label:   Comfort Level To Center
      default: U10
      choices: { U10: U10, U12: U12, U14: U14, U16: U16, U19: U19 }
                        
    comfortLevelAssist:
      type:    select
      label:   Comfort Level To Assist
      default: U10
      choices: { U10: U10, U12: U12, U14: U14, U16: U16, U19: U19 }
                        
    requestAssessment:
      type:      radio
      label:     Assessment Request
      choices:  {None: None, Informal: Informal, Formal: Formal}
      default:   None

    lodgingNights:
      type: collection
      items:
        Fri:
          type:      radio
          label:     Lodging Friday Night
          date:     '2014-04-11'
          choices:  {No: No, Yes: Yes}
          default:   No
        Sat:
          type:      radio
          label:     Lodging Saturday Night
          date:     '2014-04-12'
          choices:  {No: No, Yes: Yes}
          default:   No
                            
    lodgingWith:   { type: text, label: Lodging With,   size: 30 }
    travelingWith: { type: text, label: Traveling With, size: 30 }
    travelingFrom: { type: text, label: Traveling From, size: 30 }
                    
    teamClubAffilation:
      type:    select
      label:   Team/Club Affiliation
      default: None
      choices: 
        None: None
        Yes1: Club/Team is     in this tournament
        Yes2: Club/Team is NOT in this tournament
                        
    teamClubName: { type: text, label: Team/Club Name, size: 30 }
                             
    availabilityDays:
      type: collection
      items:
        Fri:
          type:      select
          label:     Availability Friday
          date:     '2014-04-11'
          default:   None
          choices: { None: None, Evening: Kickoff 5PM, NotSure: Not Sure }
        Sat:
          type:      select
          label:     Availability Saturday
          date:     '2014-04-12'
          default:   None
          choices: { None: None, AllDay: All Day, MorningOnly: Morning Only, AfternoonOnly: Afternoon Only, NotSure: Not Sure }
        Sun:
          type:      select
          label:     Availability Sunday
          date:     '2014-04-13'
          default:   None
          choices: { None: None, AllDay: All Day, MorningOnly: Morning Only, AfternoonOnly: Afternoon Only, NotSure: Not Sure }
                            
    notes: { type: textarea, label: Notes, rows: 5, cols: 50}
