parameters:

services:
    cerad_tourns.twig_extension:
        class:  Cerad\Bundle\TournsBundle\TwigExtension\TournsExtension
        tags:
            - { name: twig.extension }
            
    cerad_tourns.officials.export_xls:
        class:  Cerad\Bundle\TournsBundle\Officials\ExportOfficialsXLS

