parameters:

services:
    cerad_tourns.twig_extension:
        class:  Cerad\Bundle\TournsBundle\TwigExtension\TournsExtension
        arguments:  
            - '%cerad_tourn_show_configs%'
        tags:
            - { name: twig.extension }
            
    cerad_tourns.excel:
        class:  Cerad\Component\Excel\Excel
            
    cerad_tourns.officials.export_xls:
        class:  Cerad\Bundle\TournsBundle\Officials\ExportOfficialsXLS
        arguments:  
            - '@cerad_tourns.excel'
