parameters:
#    cerad_tourns.example.class: Cerad\Bundle\TournsBundle\Example

services:
#    cerad_tourns.example:
#        class: %cerad_tourns.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
