imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        mail:
            type:         fingers_crossed
            action_level: error
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: admin@zayso.org
            to_email:   ahundiak@gmail.com
            subject:   "[ZaysoError] AppTourns"
            level:      debug
assetic:
    use_controller: true

swiftmailer:
    delivery_address: %mailer_delivery_address%
