     
key:        USSF_AL_StateCup_Spring2014
arbiter:    ALYS_SOCCER_ALABAMASTATECUP_SPRING2014
slug:       StateCupSpring2014
slugPrefix: StateCup
role:       Tournament
    
fed:     USSF
fedOrg:  USSF_AL
fedRole: USSFC
                
name:    Alabama State Cup Prelims
desc:    USSF Alabama State Cup 2014 - Decatur, Alabama - May 2,3,4
    
general_url:  http://alasoccerref.org/tournaments.htm
register_url: http://zayso.org/arbiter/tourn/statecup
    
status:    Active
verified:  Yes
                
season:    Spring2014
sport:     Soccer
domain:    ALYS
domainSub: Alabama State Cup
                                
assignor:
  name:   Ohannes Younanian
  email:  ohannesy@yahoo.com
  phone:  334.477.6313
  submit: Emails your application to Ohannes Younanian and yourself.
  prefix: StateCup
  bcc:    { name: Art Hundiak, email: ahundiak@gmail.com }
  
dates:
  - { date: '2014-05-02', label: Fri, lodging: true,  search: true, avail: 5PM Kickoff }
  - { date: '2014-05-03', label: Sat, lodging: true,  search: true, avail: AllDay }
  - { date: '2014-05-04', label: Sun, lodging: false, search: true, avail: AllDay }
      
plan:
  refereeLevel:       ~                                   
  comfortLevelCenter: ~             
  comfortLevelAssist: ~
                        
  requestAssessment: ~

  lodging: ~
  lodgingWith:   ~
    
  travelingWith: ~
  travelingFrom: ~
                    
  teamClubAffilation: ~            
  teamClubName: ~
                             
  availability: ~
                            
  notes: ~
