parameters:
#    cerad_arbiter.example.class: Cerad\Bundle\ArbiterBundle\Example

services:
#    cerad_arbiter.example:
#        class: %cerad_arbiter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
