parameters:
#    cerad_arbiter.example.class: Cerad\Bundle\ArbiterBundle\Example

services:
#    cerad_arbiter.example:
#        class: %cerad_arbiter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    cerad_arbiter.schedule.tourn.arbiter.load:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Tourn\LoadArbiterSchedule
        
    cerad_arbiter.schedule.tourn.referee.save:
        class:  Cerad\Bundle\ArbiterBundle\Schedule\Tourn\SaveRefereeSchedule
