
USSF_AL_StateCupFF_Spring2014: # Index is not used
    
  info:     
    id:     USSF_AL_StateCupFF_Spring2014
    
    slugs: [statecupff, statecupff2014]
    
    arbiter: ALYS_SOCCER_ALABAMASTATECUP_SPRING2014
      
    fed:     USSF
    fedOrg:  USSF_AL
    fedRole: USSFC
        
    fedId:     USSF
    fedRoleId: USSFC
                
    title:   "Alabama State Cup Final Four"
    desc:    "USSF Alabama State Cup Final Four 2014 - Decatur, Alabama - May 9,10,11"
    
    general_url:  'http://www.huntsvillefc.org/springclassic/'
    register_url: 'http://alasoccerref.org/tournaments.htm'
    
    status:    Active
    verified:  Yes
                
    season:    SP2014
    sport:     Soccer
    group:     ALYS
    groupSub:  Alabama State Cup

    domain:    USSF
    domainSub: USSF_AL
    
    submit:  "Emails your application to Ohannes Younanian and yourself."
    prefix:   StateCupFF
             
    assignor:
      name:  "Ohannes Younanian"
      email: "ohannesy@yahoo.com"
      phone:  334.477.6313
                 
  basic:
    refereeLevel:
      type:    select
      label:   Level to Referee At
      default: Competitive
      choices: { Competitive: Competitive, Elite: Elite, Recreational: Recreational }
                                                
    comfortLevelCenter:
      type:    select
      label:   Comfort Level To Center
      default: U10
      choices: { U10: U10, U12: U12, U14: U14, U16: U16, U19: U19 }
                        
    comfortLevelAssist:
      type:    select
      label:   Comfort Level To Assist
      default: U10
      choices: { U10: U10, U12: U12, U14: U14, U16: U16, U19: U19 }
                        
    requestAssessment:
      type:      radio
      label:     Assessment Request
      choices:  {None: None, Informal: Informal, Formal: Formal}
      default:   None

    lodgingNights:
      type: collection
      items:
        Fri:
          type:      radio
          label:     Lodging Friday Night
          date:     '2014-05-09'
          choices:  {No: No, Yes: Yes}
          default:   No
        Sat:
          type:      radio
          label:     Lodging Saturday Night
          date:     '2014-05-10'
          choices:  {No: No, Yes: Yes}
          default:   No
                            
    lodgingWith:   { type: text, label: Lodging With,   size: 30 }
    travelingWith: { type: text, label: Traveling With, size: 30 }
    travelingFrom: { type: text, label: Traveling From, size: 30 }
                    
    teamClubAffilation:
      type:    select
      label:   Team/Club Affiliation
      default: None
      choices: 
        None: None
        Yes1: Club/Team is     in this tournament
        Yes2: Club/Team is NOT in this tournament
                        
    teamClubName: { type: text, label: Team/Club Name, size: 30 }
                             
    availabilityDays:
      type: collection
      items:
        Fri:
          type:      select
          label:     Availability Friday
          date:     '2014-05-09'
          default:   None
          choices: { None: None, Evening: Kickoff 5PM, NotSure: Not Sure }
        Sat:
          type:      select
          label:     Availability Saturday
          date:     '2014-05-10'
          default:   None
          choices: { None: None, AllDay: All Day, MorningOnly: Morning Only, AfternoonOnly: Afternoon Only, NotSure: Not Sure }
        Sun:
          type:      select
          label:     Availability Sunday
          date:     '2014-05-11'
          default:   None
          choices: { None: None,AllDay: All Day, MorningOnly: Morning Only, AfternoonOnly: Afternoon Only, NotSure: Not Sure }
                            
    notes: { type: textarea, label: Notes, rows: 5, cols: 50}
